export default {
  LOAD_ALL_SHOPS: 'LOAD_ALL_SHOPS',
  FILTER_SHOP_BY_TYPE: 'FILTER_SHOP_BY_TYPE',
  FILTER_SHOP_BY_NAME: 'FILTER_SHOP_BY_NAME',
  GET_REVIEWS_BY_SHOP_NAME: 'GET_REVIEWS_BT_SHOP_NAME',
  GET_REVIEWS_BY_USER_NAME: 'GET_REVIEWS_BY_USER_NAME',
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_REGISTER: 'USER_REGISTER',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  ADD_REVIEW: 'ADD_REVIEW'
}
